// Generates Radix-style 12-step palettes for the ATTK website.
//
// Two scales: `sand` (warm neutral) and `copper` (burnt orange accent).
// The base scale is generated by `radix-theme-generator` from the brand
// anchor colors, then specific steps are overridden to lock the existing
// exact site hex codes onto their natural positions in the scale. Re-run
// any time the anchors change:
//
//   node scripts/generate-palette.mjs

import { generateRadixColors } from 'radix-theme-generator';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, '../src/styles/colors');
mkdirSync(outDir, { recursive: true });

const ANCHOR_GRAY = '#2c2622';
const ANCHOR_ACCENT = '#b84c2a';
const ANCHOR_BACKGROUND = '#faf7f2';

// Existing site hex codes pinned to specific scale steps so the visual
// identity is preserved exactly. The generator's smooth interpolation fills
// the rest.
const SAND_OVERRIDES = {
  1: '#faf7f2', // body background
  3: '#f4ede4', // About section background
  5: '#ebe4da', // FAQ paragraph divider
  6: '#ddd5cb', // Pricing h3 top border
  7: '#c9bfb2', // Section borders, subtle counter color
  10: '#5a5148', // Muted body text (hero subtitle)
  11: '#3d3530', // Default paragraph text
  12: '#2c2622', // Headings, logo
};

const COPPER_OVERRIDES = {
  9: '#b84c2a', // Links, CTA bg, h3 accent
  10: '#a34122', // Accent hover
};

const result = generateRadixColors({
  appearance: 'light',
  accent: ANCHOR_ACCENT,
  gray: ANCHOR_GRAY,
  background: ANCHOR_BACKGROUND,
});

function applyOverrides(scale, overrides) {
  return scale.map((value, index) => overrides[index + 1] ?? value);
}

const sandScale = applyOverrides(result.grayScale, SAND_OVERRIDES);
const copperScale = applyOverrides(result.accentScale, COPPER_OVERRIDES);

function buildScaleCss(
  name,
  solidScale,
  alphaScale,
  wideGamutScale,
  alphaWideGamutScale
) {
  const lines = [];
  lines.push(
    '/* Generated by scripts/generate-palette.mjs — do not edit by hand. */'
  );
  lines.push('/* Run `node scripts/generate-palette.mjs` to regenerate. */');
  lines.push('');
  lines.push(':root, .light, .light-theme {');
  solidScale.forEach((hex, i) => {
    lines.push(`  --${name}-${i + 1}: ${hex};`);
  });
  alphaScale.forEach((hex, i) => {
    lines.push(`  --${name}-a${i + 1}: ${hex};`);
  });
  lines.push('}');
  lines.push('');
  lines.push('@supports (color: color(display-p3 1 1 1)) {');
  lines.push('  @media (color-gamut: p3) {');
  lines.push('    :root, .light, .light-theme {');
  wideGamutScale.forEach((color, i) => {
    lines.push(`      --${name}-${i + 1}: ${color};`);
  });
  alphaWideGamutScale.forEach((color, i) => {
    lines.push(`      --${name}-a${i + 1}: ${color};`);
  });
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const sandCss = buildScaleCss(
  'sand',
  sandScale,
  result.grayScaleAlpha,
  result.grayScaleWideGamut,
  result.grayScaleAlphaWideGamut
);

const copperCss = buildScaleCss(
  'copper',
  copperScale,
  result.accentScaleAlpha,
  result.accentScaleWideGamut,
  result.accentScaleAlphaWideGamut
);

writeFileSync(resolve(outDir, 'sand.css'), sandCss);
writeFileSync(resolve(outDir, 'copper.css'), copperCss);

console.log('Wrote:');
console.log('  src/styles/colors/sand.css');
console.log('  src/styles/colors/copper.css');
console.log('');
console.log('sand scale:', sandScale);
console.log('copper scale:', copperScale);
